### ISSUE TITLE
Nuget package includes it own copy of newtonsoft.json and restsharp

### ISSUE THREAD

**Issue by henkmeulekamp** [eneifert/ZenDeskApi#12]
Nuget package includes copied files for json and restsharp

http://nuget.org/List/Packages/ZenDeskApi

A beter way (for versioning purposes of the external dependencies) would be to use the offical way of adding dependencies; 
http://docs.nuget.org/docs/reference/nuspec-reference

Especially for newtonsoft.json that is used a lot. Having that library included as a non versioned dependency will break nugets possibility to help resolving dependency conflicts.

**Comment by eneifert** [comment]
Hey guys,

I no longer have a testing environment that I can use to keep supporting this api. Is anyone else out there willing to take this project over? Let me know and I will post in the zendesk forum to send all future requests to you.

Thanks,
Eric

**Comment by henkmeulekamp** [comment]
Hi Eric,

We will use this library more in the future, so we can do some participation from our site. I will need to invest some time to get up to speed with all ins and outs on your library before committing to anything. 

How much time does this library currently cost you to maintain it? 

Are there other contributors? 

Is zendesk not prepared to setup a test account for this project? I dont think that I will be able to support it on our company account.

**Comment by eneifert** [comment]
Hi Henkmeulekamp,

Thanks for responding. Currently I can no longer test the code and I am not really interested even asking zendesk for a sandbox because even if they gave me one I would rather spend the time on other personal projects. As for time, over the summer when I worked on it more I would spend about 2-3 hours a week answering questions and making updates but now I noticed the requests have dies off (maybe there is 1-2 a month).

As for other contributors, nicstrong (https://github.com/nicstrong) has sent me a pull request and I will let you know if he says anything to me about wanting to work more with it. I posted here https://support.zendesk.com/entries/435920 as well so someone else might respond as well.

The code is built around RestSharp, but here is a short summary as well.

There are in the code there are 3 parts: Model, RequestMethods, and the Serializers. The Model classes should be an exact representation of the data that goes back and forth from the zendesk api. The request methods set up the Create, Update, and Delete requests. And the Serializers is what translates the data from XML and JSON to c# objects. They are pretty much taken directly from the RestSharp project, but I had to make small changes here and there to get it to work with zendesk. 

The zendesk api (http://www.zendesk.com/support/api/rest-introduction) itself has probably grown up a lot since I wrote this, considering they hired a full time person to keep up with the documentation after I finished. And I haven't really looked at it in a while, so it might be worth looking over.

Let me know what else I can do for you,
Eric
