### ISSUE TITLE
Get list of forums

### ISSUE THREAD

**Issue by Mikhail-Zakharov** [eneifert/ZenDeskApi#6]
I'm using an ZendeskApi.GetForums method.

First call of this method returns correct data (List (Of Forum)). But second call returns null. Error message in ((RestSharp.RestResponseBase)(response).ErrorMessage is:

Data at the root level is invalid. Line 1, position 1

.Content contains a value that seems like correct.

What a wonder when i'm restarting my application first call returns a null with same error. The bug dissapears after a while.

**Comment by ikalatch** [comment]
I too was getting the same error - seems like it returns JSON instead of XML and the XML parser can not parse the data.

Seems like the APIs for Macros, Forums and Organizations have been deprecated. There is a new header in the response suggesting to use URL prefixes for these "api/v1﻿/".

GetForums() failed for the sandbox when called through either the old or the new URLs. The workaround was to add  + ".xml"﻿ in the Forum.cs to make it work:

```
    private string _forums = "api/v1/forums";
    public List<Forum> GetForums()
    {
        return GetCollection<Forum>(_forums + ".xml");
    }
```

Cheers!

**Comment by eneifert** [comment]
Great find! It seems Zendesk is in the process of switching over their default data type. They originally had some missing data from the json calls so I went with xml parsing everywhere. I will go through and try to make sure that the ".xml" is explicitly stated.
