### ISSUE TITLE
s/ZenDesk/Zendesk

### ISSUE THREAD

**Issue by jakeisonline** [eneifert/ZenDeskApi#8]
Excellent job on the wrapper. Just one little thing, it's "Zendesk" and not "ZenDesk" ;)

**Comment by deepthawtz** [comment]
If there was irony in the misspelling (e.g., a PHP Netflix client named netphlix or something) I would see more humor in it.

Definitely love the fact that you've taken the time to work on this and I don't want to quench that enthusiasm of yours. I think fixing the typo in the name would be tasteful.

One possible solution, since you mentioned that you were concerned about developers who already cloned the repository is to leave this repository as is and add a note in the README pointing to the new location. That way people have time to adjust.

**Comment by eneifert** [comment]
Ok guys, thanks for pointing this out. The wrapper has now been renamed to "ZenDeskApi". Let me know if you see anything else.
